"""empty message

Revision ID: 12e5669dc2d3
Revises: None
Create Date: 2015-09-22 18:01:21.622100

"""

# revision identifiers, used by Alembic.
revision = '12e5669dc2d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
